name: ClanWar
version: ${project.version}
main: eu.iteije.clanwar.ClanWar
api-version: 1.13
authors: [ iTeije ]
website: https://iteije.eu
depend:
  - Citizens

commands:
  setspawn:
    usage: /<command>
  clan:
    usage: /<command>
  gamemanager:
    usage: /<command>